### ISSUE TITLE
Getting a Fatal error when trying to view a template

### ISSUE THREAD

**Issue by gmclelland** [decadeofdefeat/church-website-processwire#1]
Thanks for sharing this profile.  It's great to see how other people build Processwire websites.

One thing I noticed is that if I try to visit /admin/setup/template/edit?id=103, I get a fatal error.

Error: Cannot redeclare class Julian (line 13 of /Users/glenn/websites/pwchurch/wwwroot/site/modules/LibJulian/julian/Julian.php) 

I think the code in LibJulian.module should be

``` php
  private function julianLoader(){
    include_once "julian/Julian.php";
    include_once "julian/Julian_Day.php";
    include_once "julian/Julian_Week.php";
    include_once "julian/Julian_Event.php";
  }
```

instead of this:

``` php
  private function julianLoader(){
    include "julian/Julian.php";
    include "julian/Julian_Day.php";
    include "julian/Julian_Week.php";
    include "julian/Julian_Event.php";
  }
```

Hope that helps

**Comment by decadeofdefeat** [comment]
Hmm, never had a fatal error before because of the Julian module. I updated it. Thanks!
