### ISSUE TITLE
Live service

### ISSUE THREAD

**Issue by JayGreentree-Codes** [decadeofdefeat/church-website-processwire#2]
How do I enable the Live notification when we are live streaming?

**Comment by decadeofdefeat** [comment]
You can put all the logic for the live streaming notification in the includes/functions.inc. I stripped my church's logic out, by you could literally do something as easy as this for a repeating Sunday service from 9am to 10:30am:

```
wire("config")->live = false; 
if ((date("w") == 0) && (date("Hi")>900) && (date("Hi")<1030)) {
    wire("config")->live = true;    
}
```

**Comment by JayGreentree-Codes** [comment]
Thanks for the help with some customization I was able to get it working how I want
![2016_09_04_14_41_58_thursday_church](https://cloud.githubusercontent.com/assets/215971/18233182/eab158e4-72ad-11e6-9cd5-11aa3cb53631.png)
